### PR TITLE
for issue #116

### PR DESCRIPTION
**Pull request by 0-harshit-0**
added functionality to connect using URL

### CODE REVIEW

**Comment by atagar** [comment]
Hi harshit, sorry for the long delay. This is a fine attempt but has some issues...

1. It breaks both method's pydocs. The first comment block of a method is special in that Sphinx uses it to generate API documentation.
2. Rather than allowing hostnames for the address argument it would be better if we added a new 'hostname' argument. This way the argument isn't a misnomer and can't accidently trigger a DNS lookup (which could leak data in some environments).
3. This change would require unit and integ test coverage.

**Comment by 0-harshit-0** [comment]
oh ok got it.

**Comment by 0-harshit-0** [comment]
hello, I have made a new commit to this pull request.

**Comment by atagar** [comment]
It's been a while without tests being added so closing.

**Pull request closed without merging**
