### PR TITLE
fix: fix regex and update authority URL

### LINKED ISSUE #134: stem.directory.Authority.from_remote() will break when GitWeb shuts down
Hello,

first off, thank you for your library! I apologize in advance if this is just us using it wrongly, I'm new to the subject, and would definitely appreciate any pointers in the right direction.

We are using `stem` to retrieve the directory files for https://github.com/c4dt/lightarti-rest (for details see https://github.com/c4dt/lightarti-directory). However we have currently problems that seem to be related to an outdated `v3ident` value for `moria1` that seems to get retrieved by `stem` (see here https://github.com/torproject/tor/commit/72b04a5aa42dd2729cf9fe9452e559c29466b250)

Here's a small script that mimicks what we're doing:

```
python3
Python 3.11.4 (main, Jun  7 2023, 10:13:09) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import stem
>>> stem.__version__
'1.8.2'
>>> import stem.directory
>>> for name, authority in `stem.directory.Authority.from_cache()`.items():
...     print((name, authority.v3ident))
... 
('moria1', 'D586D18309DED4CD6D57C18FDB97EFA96D330566') <-- old v3ident value
[...]
>>> import stem.descriptor
>>> import stem.descriptor.remote
>>> downloader = stem.descriptor.remote.DescriptorDownloader()
>>> temp = downloader.get_consensus(document_handler=stem.descriptor.DocumentHandler.DOCUMENT, microdescriptor=True).run()[0]
>>> [auth.v3ident for auth in temp.directory_authorities]
['0232AF901C31A04EE9848595AF9BB7620D4C5B2E', '14C131DFC5C6F93646BE72FA1401C02A8DF2E8B4', '23D15D965BC35114467363C165C4F724B64B4F66', '27102BC123E7AF1D4741AE047E160C91ADC76B21', '49015F787433103580E3B66A1707A00E60F2D15B', 'E8A9C45EDE6D711294FADF8E7951F4DE6CA56B58', 'ED03BB616EB2F60BEC80151114BB25CEF515B226', 'F533C81CEF0BC0267857C99B2F471ADF249FA232'] <-- last element is new v3ident value
``` 

We then compare the v3idents retrieved by the first part with those retrieved in the second part (specifically we look for moria1) and come up with an empty list, as the first one has the old value, and the second one the new value (the last element).

Is this the expected behaviour for `stem.directory.Authority.from_cache()`?

Thank you in advance!

### PR DESCRIPTION
**Pull request by PascalinDe**
closes #134

### CODE REVIEW

**Comment by PascalinDe** [comment]
Hi @atagar, is this PR OK? the unit test output is the same as on the current master HEAD for me, I'm currently looking into how to run the integration tests

**Comment by atagar** [comment]
Hi Carine. These look good to me but I didn't check the tests. Your [other pull request](https://github.com/torproject/stem/issues/136) is built on top of this so I figured it would be simpler to discuss it there.

**Comment by PascalinDe** [comment]
hi Damian, I rebased the other PR so that this one can be evaluated independently

while doing so, I found that this PR actually does break a test, just a test that was already failing, meaning it now fails in a different way

on the master branch, the output is

```
File "stem/descriptor/remote.py", line 787, in remote.py
Failed example:
    my_router_status_entry = list(filter(lambda desc: desc.nickname == 'caersidi', consensus))[0]
Exception raised:
    Traceback (most recent call last):
      File "/usr/local/lib/python3.11/doctest.py", line 1351, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest remote.py[2]>", line 1, in <module>
        my_router_status_entry = list(filter(lambda desc: desc.nickname == 'caersidi', consensus))[0]
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
    IndexError: list index out of range
```

whereas on this branch

```
File "stem/descriptor/remote.py", line 787, in remote.py
Failed example:
    my_router_status_entry = list(filter(lambda desc: desc.nickname == 'caersidi', consensus))[0]
Exception raised:
    Traceback (most recent call last):
      File "/usr/local/lib/python3.11/doctest.py", line 1351, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest remote.py[2]>", line 1, in <module>
        my_router_status_entry = list(filter(lambda desc: desc.nickname == 'caersidi', consensus))[0]
                                                                                       ^^^^^^^^^
    NameError: name 'consensus' is not defined

```
this is only the case for Python 3.11; for 3.8, 3.9 and 3.10 the error is the same for both branches, I'm looking into it

the rest of the unit tests have the same output, I could not yet get the integration tests to run

**Comment by PascalinDe** [comment]
same results on both master and this branch for the integration tests

**Comment by PascalinDe** [comment]
didn't take into account that the GitLab URL might change, using the 'Permalink' URL for the moment...

I'll put this back into 'Draft' state until I figure out what the proper GitLab URL is to follow the new releases but not break (as the one I used before did), since I guess that the 'Permalink' URL points to a specific revision

**Comment by PascalinDe** [comment]
* [x] same results for unit tests Python 3.8-3.11
* [x] same results for integration tests Python 3.8-3.11



same results for both the unit tests and integration tests for this branch and the master branch for Python 3.8-3.11

**Comment by PascalinDe** [comment]
rebased the PR to the current HEAD

**Pull request merged**
